### ISSUE TITLE
linux-4.1.y - broken hdmi

### ISSUE THREAD

**Issue by heapxor** [xbianonpi/xbian-sources-kernel#1]
Hi,

the hdmi->Dvi output doesnt work with 4.1.13, could you please take a look on it?

thank you

**Comment by heapxor** [comment]
doesnt work with kernel 4.4 ...

**Comment by mkreisl** [comment]
@heapxor 
A little bit more information could be very useful
I tested it with my hardware (RPi1, TV DVI Input 1280x768 Resolution), no problem
